# SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-2.0-or-later
version = 1
SPDX-PackageName = "desktop"
SPDX-PackageSupplier = "Nextcloud <info@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/desktop"

[[annotations]]
path = ["translations/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2012 ownCloud Inc. and ownCloud translators, 2018 Nextcloud GmbH and Nextcloud translators"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["admin/win/nsi/l10n/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 ownCloud Inc. and ownCloud translators, 2020 Nextcloud GmbH and Nextcloud translators"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["nextcloud.client-desktop/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Nextcloud GmbH and Nextcloud translators"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["shell_integration/windows/NCOverlays/resource.h", "shell_integration/windows/NCOverlays/NCOverlays.def", "shell_integration/icons/SVG/*.svg", "shell_integration/icons/Sidebar/sidebar_icon_*_18.png", "shell_integration/icons/icns/*.icns", "shell_integration/icons/*x*/oC_*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 ownCloud GmbH"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = [
    "admin/osx/container-migration.plist.cmake",
    "shell_integration/MacOSX/TransifexStringCatalogSanitizer/Package.swift",
    "shell_integration/MacOSX/TransifexStringCatalogSanitizer/Package.resolved",
    "shell_integration/MacOSX/TransifexStringCatalogSanitizer/README.md",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["admin/osx/mac-crafter/Package.resolved", "shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = [
    "shell_integration/MacOSX/NextcloudIntegration/.gitignore",
    "shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.pbxproj", 
    "shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.xcworkspace/contents.xcworkspacedata", 
    "shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist", 
    "shell_integration/MacOSX/NextcloudIntegration/NextcloudIntegration.xcodeproj/xcshareddata/xcschemes/Nextcloud Developer Client.xcscheme",
    "shell_integration/MacOSX/NextcloudIntegration/README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Localizable.xcstrings", "shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Localizable.xcstrings", "shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Assets.xcassets/*", "shell_integration/MacOSX/NextcloudIntegration/FileProviderExt/Assets.xcassets/FileProviderDomainSymbol.symbolset/*", "shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Assets.xcassets/*", "shell_integration/MacOSX/NextcloudIntegration/FileProviderUIExt/Assets.xcassets/FileProviderDomainSymbol.symbolset/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015 ownCloud GmbH, 2022 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["shell_integration/icons/nopadding/*/*.png", "shell_integration/icons/nopadding/SVG/*.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015 ownCloud GmbH"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["shell_integration/windows/NCContextMenu/NCContextMenu.rc", "shell_integration/windows/NCOverlays/NCOverlay.rc", "shell_integration/windows/NCUtil/NCUtil.rc"]
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2015 ownCloud GmbH, 2023 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = ["shell_integration/windows/NCOverlays/ico/Error.ico", "shell_integration/windows/NCOverlays/ico/OK.ico", "shell_integration/windows/NCOverlays/ico/OK_Shared.ico", "shell_integration/windows/NCOverlays/ico/Sync.ico", "shell_integration/windows/NCOverlays/ico/Warning.ico", ""]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 ownCloud GmbH"
SPDX-License-Identifier = "LGPL-2.1-or-later"

[[annotations]]
path = ["doc/images/main_dialog_christine.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = [".tx/config"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["man/index.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 ownCloud GmbH"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = ["man/nextcloud.1.rst", "man/nextcloudcmd.1.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 ownCloud GmbH, 2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = [".tx/nextcloud.client-desktop/*_translation", "theme/*/state-error.svg", "theme/*/state-info.svg", "theme/*/state-offline.svg", "theme/*/state-ok.svg", "theme/*/state-pause.svg", "theme/*/state-sync.svg", "theme/*/state-warning.svg", "theme/colored/error.svg", "theme/colored/info.svg", "theme/colored/offline.svg", "theme/colored/ok.svg", "theme/colored/pause.svg", "theme/colored/sync.svg", "theme/colored/warning.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"

[[annotations]]
path = ["admin/osx/installer-background.png","admin/osx/installer-background.svg","admin/osx/installer-background_2x.png", "admin/win/msi/gui/banner.bmp","admin/win/msi/gui/banner.svg","admin/win/msi/gui/dialog.bmp", "admin/win/nsi/installer.ico", "admin/win/nsi/page_header.bmp", "admin/win/nsi/welcome.bmp", "doc/_shared_assets/themes/nextcloud_com/static/img/logo.svg", "doc/_shared_assets/static/logo-blue.pdf","doc/_shared_assets/static/logo-blue.png", "doc/logo-blue.pdf", "theme/talk-app.svg", "theme/*/deck.svg", "theme/*/talk-app.svg","theme/*/wizard-nextcloud.png","theme/*/wizard-nextcloud.svg","theme/*/wizard-nextcloud@2x.png","theme/*/wizard-talk.png","theme/*/wizard-talk.svg","theme/*/wizard-talk@2x.png", "theme/colored/talk-bordered.svg", "theme/colored/icons/Nextcloud-icon-win-folder.svg", "theme/colored/Nextcloud-icon-square.svg", "theme/colored/Nextcloud-icon.svg", "theme/colored/Nextcloud-macOS-icon.svg", "theme/colored/Nextcloud-macOS-sidebar.svg", "theme/colored/Nextcloud-w10startmenu.svg", "theme/colored/Nextcloud-w10starttile.png", "theme/colored/wizard_logo.png", "theme/colored/wizard_logo.svg", "theme/colored/wizard_logo@2x.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Nextcloud GmbH"
SPDX-License-Identifier = "LicenseRef-NextcloudTrademarks"

[[annotations]]
path = ["theme/white/error.svg", "theme/black/error.svg","theme/white/warning.svg", "theme/black/warning.svg", "theme/white/info.svg", "theme/black/info.svg", "theme/info.svg", "theme/white/nextcloud/*.svg", "theme/black/nextcloud/*.svg", "theme/colored/nextcloud/*.svg", "theme/black/label.svg", "theme/white/label.svg", "theme/colored/user-status-*.svg", "theme/account.svg","theme/add.svg","theme/change.svg","theme/chevron-double-up.svg","theme/close.svg","theme/confirm.svg","theme/copy.svg","theme/delete.svg","theme/external.svg","theme/files.svg","theme/lock-broken.svg","theme/lock-http.svg","theme/lock-https.svg","theme/lock.svg","theme/magnifying-glass.svg","theme/more.svg","theme/network.svg","theme/public.svg","theme/reply.svg","theme/send.svg","theme/settings.svg","theme/share.svg","theme/sync-arrow.svg", "theme/black/account-group.svg","theme/black/clear.svg","theme/black/expand-less-black.svg","theme/black/folder-group.svg","theme/black/search.svg", "theme/colored/add-bordered.svg", "theme/colored/change-bordered.svg", "theme/colored/delete-bordered.svg", "theme/colored/delete.svg", "theme/*/activity.svg", "theme/*/add.svg","theme/*/bell.svg","theme/*/calendar.svg","theme/*/caret-down.svg","theme/*/change.svg","theme/*/close.svg","theme/*/comment.svg","theme/*/confirm.svg","theme/*/control-next.svg","theme/*/control-prev.svg","theme/*/edit.svg","theme/*/email.svg","theme/*/external.png","theme/*/external.svg","theme/*/external@2x.png","theme/*/folder.png","theme/*/folder.svg","theme/*/folder@2x.png","theme/*/more-apps.svg","theme/*/nc-assistant-app.svg","theme/*/settings.svg","theme/*/user.svg","theme/*/wizard-files.png","theme/*/wizard-files.svg","theme/*/wizard-files@2x.png","theme/*/wizard-groupware.png","theme/*/wizard-groupware.svg","theme/*/wizard-groupware@2x.png", "theme/cfapishellext_custom_states/0-locked.svg","theme/cfapishellext_custom_states/1-shared.svg","theme/cfapishellext_custom_states/1024-0-locked.png","theme/cfapishellext_custom_states/1024-1-shared.png","theme/cfapishellext_custom_states/128-0-locked.png","theme/cfapishellext_custom_states/128-1-shared.png","theme/cfapishellext_custom_states/24-0-locked.png","theme/cfapishellext_custom_states/24-1-shared.png","theme/cfapishellext_custom_states/256-0-locked.png","theme/cfapishellext_custom_states/256-1-shared.png","theme/cfapishellext_custom_states/32-0-locked.png","theme/cfapishellext_custom_states/32-1-shared.png","theme/cfapishellext_custom_states/40-0-locked.png","theme/cfapishellext_custom_states/40-1-shared.png","theme/cfapishellext_custom_states/48-0-locked.png","theme/cfapishellext_custom_states/48-1-shared.png","theme/cfapishellext_custom_states/512-0-locked.png","theme/cfapishellext_custom_states/512-1-shared.png","theme/cfapishellext_custom_states/64-0-locked.png","theme/cfapishellext_custom_states/64-1-shared.png", "theme/backup.svg", "theme/convert_to_text.svg", "theme/file-open.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2025 Google LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["Nextcloud Desktop Client.xcworkspace/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
