# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: LGPL-3.0-or-later
version = 1
PDX-PackageName = "NextcloudFileProviderKit"
SPDX-PackageSupplier = "Nextcloud <info@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/nextcloudfileproviderkit"

[[annotations]]
path = [
    "NextcloudFileProviderKit.png", 
    "NextcloudFileProviderKit.pxd", 
    "NextcloudFileProviderKit.svg"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud GmbH"
SPDX-License-Identifier = "LicenseRef-NextcloudTrademarks"

[[annotations]]
path = [
    ".gitignore",
    ".swiftformat",
    ".swift-version",
    "Package.swift",
    "Sources/NextcloudFileProviderKit/Documentation.docc/theme-settings.json"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "LGPL-3.0-or-later"
