name: 'Close stale needs info issues'
on:
    schedule:
        -   cron: '30 */8 * * *'

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/stale@v9
                with:
                    operations-per-run: 1500
                    days-before-stale: 28
                    days-before-close: 14
                    days-before-pr-close: -1
                    only-labels: 'needs info'
                    stale-issue-label: 'stale needs info'
                    exempt-issue-labels: 'bug'
                    stale-issue-message: 'This issue has been marked as "needs info" 4 weeks ago.
                                        Please take a look again and try to provide the information requested,
                                        otherwise the issue will be automatically closed in 2 weeks. Thank you!'
                    close-issue-message: "This bug report is getting automatically closed due to no answer
                                          since the issue has been staled. Thank you!"
                    exempt-all-pr-milestones: true
