name: 'Close stale issues'
on:
    schedule:
        -   cron: '30 */8 * * *'

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/stale@v9
                with:
                    operations-per-run: 1500
                    days-before-stale: 28
                    days-before-close: 14
                    days-before-pr-close: -1
                    only-labels: 'bug,need info'
                    exempt-issue-labels: 'approved'
                    stale-issue-message: 'This bug report did not receive an update in the last 4 weeks.
                                        Please take a look again and update the issue with new details,
                                        otherwise the issue will be automatically closed in 2 weeks. Thank you!'
                    close-issue-message: "This bug report is getting automatically closed due to no answer
                                          since the issue has been staled. Thank you!"
                    exempt-all-pr-milestones: true
